## ?????
#server:
#  port: 8081

spring:
  # messageSource
#  messages:
#    basename: messages, ValidationMessages

  # JDBCドライバを指定
  datasource:
    driver-class-name: org.h2.Driver
    # データベースのURL。メモリ上にtestdbを作成しますよ、と指定。
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      # コンソールを有効化
      enabled: true
      path: /h2-console
