INSERT INTO TSET_TABLE(TEXT1, TEXT2) VALUES ('text1_1', 'text2_1');
INSERT INTO TSET_TABLE(TEXT1, TEXT2) VALUES ('text1_2', 'text2_2');
INSERT INTO TSET_TABLE(TEXT1, TEXT2) VALUES ('text1_3', 'text2_3');