INSERT INTO TSET_TABLE(TEXT1, TEXT2) VALUES ('text1_1', '1');
INSERT INTO TSET_TABLE(TEXT1, TEXT2) VALUES ('text1_2', '0');
INSERT INTO TSET_TABLE(TEXT1, TEXT2) VALUES ('text1_3', '1');
INSERT INTO TSET_TABLE(TEXT1, TEXT2) VALUES ('text1_4', '1');